require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExerciseTextsController do

  # This should return the minimal set of attributes required to create a valid
  # ExerciseText. As you add validations to ExerciseText, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "content" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseTextsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exercise_texts as @exercise_texts" do
      exercise_text = ExerciseText.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exercise_texts).should eq([exercise_text])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise_text as @exercise_text" do
      exercise_text = ExerciseText.create! valid_attributes
      get :show, {:id => exercise_text.to_param}, valid_session
      assigns(:exercise_text).should eq(exercise_text)
    end
  end

  describe "GET new" do
    it "assigns a new exercise_text as @exercise_text" do
      get :new, {}, valid_session
      assigns(:exercise_text).should be_a_new(ExerciseText)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise_text as @exercise_text" do
      exercise_text = ExerciseText.create! valid_attributes
      get :edit, {:id => exercise_text.to_param}, valid_session
      assigns(:exercise_text).should eq(exercise_text)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExerciseText" do
        expect {
          post :create, {:exercise_text => valid_attributes}, valid_session
        }.to change(ExerciseText, :count).by(1)
      end

      it "assigns a newly created exercise_text as @exercise_text" do
        post :create, {:exercise_text => valid_attributes}, valid_session
        assigns(:exercise_text).should be_a(ExerciseText)
        assigns(:exercise_text).should be_persisted
      end

      it "redirects to the created exercise_text" do
        post :create, {:exercise_text => valid_attributes}, valid_session
        response.should redirect_to(ExerciseText.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise_text as @exercise_text" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseText.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_text => { "content" => "invalid value" }}, valid_session
        assigns(:exercise_text).should be_a_new(ExerciseText)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseText.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_text => { "content" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise_text" do
        exercise_text = ExerciseText.create! valid_attributes
        # Assuming there are no other exercise_texts in the database, this
        # specifies that the ExerciseText created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExerciseText.any_instance.should_receive(:update_attributes).with({ "content" => "MyText" })
        put :update, {:id => exercise_text.to_param, :exercise_text => { "content" => "MyText" }}, valid_session
      end

      it "assigns the requested exercise_text as @exercise_text" do
        exercise_text = ExerciseText.create! valid_attributes
        put :update, {:id => exercise_text.to_param, :exercise_text => valid_attributes}, valid_session
        assigns(:exercise_text).should eq(exercise_text)
      end

      it "redirects to the exercise_text" do
        exercise_text = ExerciseText.create! valid_attributes
        put :update, {:id => exercise_text.to_param, :exercise_text => valid_attributes}, valid_session
        response.should redirect_to(exercise_text)
      end
    end

    describe "with invalid params" do
      it "assigns the exercise_text as @exercise_text" do
        exercise_text = ExerciseText.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseText.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_text.to_param, :exercise_text => { "content" => "invalid value" }}, valid_session
        assigns(:exercise_text).should eq(exercise_text)
      end

      it "re-renders the 'edit' template" do
        exercise_text = ExerciseText.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseText.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_text.to_param, :exercise_text => { "content" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise_text" do
      exercise_text = ExerciseText.create! valid_attributes
      expect {
        delete :destroy, {:id => exercise_text.to_param}, valid_session
      }.to change(ExerciseText, :count).by(-1)
    end

    it "redirects to the exercise_texts list" do
      exercise_text = ExerciseText.create! valid_attributes
      delete :destroy, {:id => exercise_text.to_param}, valid_session
      response.should redirect_to(exercise_texts_url)
    end
  end

end
